apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azure-vote.fullname" . }}-front
  labels:
    {{- include "azure-vote.front.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.votefront.replicaCount }}
  selector:
    matchLabels:
      {{- include "azure-vote.front.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        {{- include "azure-vote.front.labels" . | nindent 8 }}
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: azure-vote-front
        image: "{{ .Values.votefront.image.repository }}:{{ .Values.votefront.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.votefront.image.pullPolicy }}
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "{{ include "azure-vote.fullname" . }}-back"