apiVersion: v1
kind: Service
metadata:
  name: {{ include "azure-vote.fullname" . }}-front
  labels:
    {{- include "azure-vote.front.labels" . | nindent 4 }}
spec:
  type: {{ if .Values.ingress.enabled }}ClusterIP{{ else }}LoadBalancer{{ end }}
  ports:
  - port: 80
  selector:
    {{- include "azure-vote.front.selectorLabels" . | nindent 4 }}