apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
spec:
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        env:
        - name: Demo
          valueFrom:
            configMapKeyRef:
              name: config
              key: Demo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: config-volume
            mountPath: /app-config
      volumes:
      - name: config-volume
        configMap:
          name: kuard-file-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  Demo:  "PwC jest Super"
  redis: "redis-master"
  asb-namespace: "blablabla"